version: "3.9"

services:

  redis:

    image: redis

    ports:
      - "6379:6379"

  fastapi:

    build: .

    ports:
      - "8000:8000"

    depends_on:
      - redis
      - mysql

    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: movie_db
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_password

  prometheus:

    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - fastapi

  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    volumes:
      - grafana-data:/var/lib/grafana


  mysql:
    image: mysql:8.4
    container_name: movie-mysql

    environment:
      MYSQL_ROOT_PASSWORD: sqlroot
      MYSQL_DATABASE: movie_db
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  grafana-data:
  mysql_data:
